---
- hosts: all
  connection: paramiko

  tasks:
    - name: Ping hosts
      ping: ~
      tags:
        - ping

    - name: OS version information
      debug:
        msg: "Host OS: {{ ansible_system }} {{ ansible_distribution }} {{ ansible_distribution_version }}"
      tags:
        - info_os

    - name: Create user
      block:
        - set_fact:
            rand_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation length=24') }}"

        - name: Create mgmt user account
          user:
            name: "{{ mgmt_usr }}"
            password: "{{ rand_pass | password_hash('sha512') }}"
            groups: "{{ mgmt_grp | default('systemd-journal') }}"
            append: yes
            shell: "/bin/bash"
            state: present

        - name: Allows user to execute commands as root
          lineinfile:
            path: "/etc/sudoers.d/{{ mgmt_usr }}"
            line: "{{ mgmt_usr }} ALL=(ALL) NOPASSWD: ALL"
            state: present
            mode: 0440
            create: yes
            validate: 'visudo -cf %s'

        - name: Generation OpenSSH key
          openssh_keypair:
            path: "{{ inventory_dir }}/id_ssh_rsa"
          register: gen_openssh_key
          when: ssh_pub_path is undefined

        - name: 1
          debug:
            var: gen_openssh_key
          

        - set_fact:
            ssh_pub_key: "{{ lookup('file', '{{ ssh_pub_path }}/*.pub') }}"
          when: ssh_pub_path is defined

        - name: Add authorized_key took from file
          authorized_key:
            user: "{{ mgmt_usr }}"
            state: present
            key: "'{{ ssh_pub_key }}"

        - debug:
            msg: "Save your password from mgmt account: {{ rand_pass }}"
      tags:
        - create_mgmt_usr